{% set python_min = "3.10" %}
{% set name = "pontibus" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/pontibus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f3a23c44af7b576a92b9fef94e87c6fe3bc8dfd7516ae61c22c09925412b2ec5

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - gufe >=1.2.0
    - openfe >=1.3.0
    - openmm <8.2.0
    - openmmtools >0.24
    - openff-interchange >=0.4.0
    - openff-nagl-base >=0.3.3
    - pydantic >=2.0
    - python >={{ python_min }}
    - rdkit !=2024.03.06

test:
  imports:
    - pontibus
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - python -c "import pontibus; assert(pontibus.__version__ == '0.0.2')"
    - pytest -v --pyargs pontibus

about:
  home: https://github.com/OpenFreeEnergy/pontibus
  summary: 'pontibus: experimental FF validation Protocols'
  description: |
    Experimental OpenFE Protocols for Force Field Evaluation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pontibus.readthedocs.io/
  dev_url: https://github.com/OpenFreeEnergy/pontibus

extra:
  recipe-maintainers:
    - IAlibay
